### ISSUE TITLE
mp_api - pydantic again? 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_atomistics#1094]
```
Traceback (most recent call last):
  File "/home/jovyan/demo.py", line 2, in <module>
    from pyiron_atomistics import Project
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pyiron_atomistics/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pyiron_atomistics/project.py", line 34, in <module>
    from pyiron_atomistics.atomistics.structure.factory import StructureFactory
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pyiron_atomistics/atomistics/structure/factory.py", line 39, in <module>
    from pyiron_atomistics.atomistics.structure.factories.materialsproject import (
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pyiron_atomistics/atomistics/structure/factories/materialsproject.py", line 2, in <module>
    from mp_api.client import MPRester
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/mp_api/client/__init__.py", line 5, in <module>
    from .core import MPRestError
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/mp_api/client/core/__init__.py", line 1, in <module>
    from .client import BaseRester, MPRestError
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/mp_api/client/core/client.py", line 20, in <module>
    from emmet.core.utils import jsanitize
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/emmet/core/utils.py", line 25, in <module>
    from emmet.core.settings import EmmetSettings
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/emmet/core/settings.py", line 12, in <module>
    from pydantic import BaseSettings, Field, root_validator
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pydantic/__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pydantic/_migration.py", line 279, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0/migration/#basesettings-has-moved-to-pydantic-settings for more details.
```

**Comment by pmrv** [comment]
I've reported the bug upstream and will add a small test so we can catch this earlier in the future.

**Comment by jan-janssen** [comment]
The conda package should be fixed once https://github.com/conda-forge/emmet-core-feedstock/pull/97 and https://github.com/conda-forge/emmet-core-feedstock/pull/98 become available.

**Comment by jan-janssen** [comment]
```
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/pyiron_base/pyiron_atomistics/tests/vasp/test_vasprun.py", line 9, in <module>
    from pyiron_atomistics.vasp.vasprun import Vasprun, VasprunError
  File "/home/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/vasp/vasprun.py", line 13, in <module>
    from pyiron_atomistics.dft.waves.electronic import ElectronicStructure
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/pyiron_atomistics/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/pyiron_atomistics/project.py", line 34, in <module>
    from pyiron_atomistics.atomistics.structure.factory import StructureFactory
  File "/home/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/atomistics/structure/factory.py", line 39, in <module>
    from pyiron_atomistics.atomistics.structure.factories.materialsproject import (
  File "/home/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/atomistics/structure/factories/materialsproject.py", line 2, in <module>
    from mp_api.client import MPRester
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/mp_api/client/__init__.py", line 5, in <module>
    from .core import MPRestError
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/mp_api/client/core/__init__.py", line 1, in <module>
    from .client import BaseRester, MPRestError
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/mp_api/client/core/client.py", line 20, in <module>
    from emmet.core.utils import jsanitize
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/emmet/core/utils.py", line 25, in <module>
    from emmet.core.settings import EmmetSettings
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/emmet/core/settings.py", line 14, in <module>
    from pydantic.types import PyObject
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/pydantic/_migration.py", line 285, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic.types:PyObject` has been removed in V2.
```

**Comment by XuShuqi7** [comment]
Hi all,

I am new user for the mp_api. It seems that I am confronting the same issue.

```Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
[Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mp_api.client import MPRester
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shuqixu/opt/miniconda3/lib/python3.9/site-packages/mp_api/client/__init__.py", line 5, in <module>
    from .core import MPRestError
  File "/Users/shuqixu/opt/miniconda3/lib/python3.9/site-packages/mp_api/client/core/__init__.py", line 1, in <module>
    from .client import BaseRester, MPRestError
  File "/Users/shuqixu/opt/miniconda3/lib/python3.9/site-packages/mp_api/client/core/client.py", line 20, in <module>
    from emmet.core.utils import jsanitize
  File "/Users/shuqixu/opt/miniconda3/lib/python3.9/site-packages/emmet/core/utils.py", line 25, in <module>
    from emmet.core.settings import EmmetSettings
  File "/Users/shuqixu/opt/miniconda3/lib/python3.9/site-packages/emmet/core/settings.py", line 12, in <module>
    from pydantic import BaseSettings, Field, root_validator
  File "/Users/shuqixu/opt/miniconda3/lib/python3.9/site-packages/pydantic/__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
  File "/Users/shuqixu/opt/miniconda3/lib/python3.9/site-packages/pydantic/_migration.py", line 279, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0/u/import-error```

**Comment by jan-janssen** [comment]
https://github.com/conda-forge/admin-requests/pull/748

**Comment by jan-janssen** [comment]
It should be fixed by https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/476 - at least for the conda package, restricting it to `pydantic<2`.

**Comment by munrojm** [comment]
I have also fixed this upstream in `emmet-core`.

**Comment by XuShuqi7** [comment]
Thanks @jan-janssen ! I succeed in solving my issue by ```pip install mp-api "pydantic >=1.10.2,<2"```.

**Comment by siyuere** [comment]
> Thanks @jan-janssen ! I succeed in solving my issue by `pip install mp-api "pydantic >=1.10.2,<2"`.

Hi I run this, but when importing MPRester, it's still showing the same error as your previous one

**Comment by XuShuqi7** [comment]
> > Thanks @jan-janssen ! I succeed in solving my issue by `pip install mp-api "pydantic >=1.10.2,<2"`.
> 
> Hi I run this, but when importing MPRester, it's still showing the same error as your previous one

Hi @siyuere, maybe you can try ```pip uninstall mp-api``` and install again, hoping it works.

**Comment by siyuere** [comment]
> > > Thanks @jan-janssen ! I succeed in solving my issue by `pip install mp-api "pydantic >=1.10.2,<2"`.
> > 
> > 
> > Hi I run this, but when importing MPRester, it's still showing the same error as your previous one
> 
> Hi @siyuere, maybe you can try `pip uninstall mp-api` and install again, hoping it works.

I tried `pip install -U mp-api` and it works. Thanks!
